# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto_files/domain.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto_files/domain.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18proto_files/domain.proto\x12\x11kc_push.events.v1\"!\n\x13ProjectCreatedEvent\x12\n\n\x02id\x18\x01 \x01(\t\"!\n\x13ProjectDeletedEvent\x12\n\n\x02id\x18\x01 \x01(\t\"P\n\x18\x41ndroidPackageAddedEvent\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x0cpackage_name\x18\x02 \x01(\t\x12\x12\n\nproject_id\x18\x03 \x01(\t\"(\n\x1a\x41ndroidPackageRemovedEvent\x12\n\n\x02id\x18\x01 \x01(\t\"S\n\x1a\x41ndroidSignatureAddedEvent\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1a\n\x12\x61ndroid_package_id\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\"*\n\x1c\x41ndroidSignatureRemovedEvent\x12\n\n\x02id\x18\x01 \x01(\t\"=\n\x18ServiceTokenCreatedEvent\x12\r\n\x05value\x18\x01 \x01(\t\x12\x12\n\nproject_id\x18\x02 \x01(\t\"=\n\x18ServiceTokenRemovedEvent\x12\r\n\x05value\x18\x01 \x01(\t\x12\x12\n\nproject_id\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto_files.domain_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROJECTCREATEDEVENT']._serialized_start=47
  _globals['_PROJECTCREATEDEVENT']._serialized_end=80
  _globals['_PROJECTDELETEDEVENT']._serialized_start=82
  _globals['_PROJECTDELETEDEVENT']._serialized_end=115
  _globals['_ANDROIDPACKAGEADDEDEVENT']._serialized_start=117
  _globals['_ANDROIDPACKAGEADDEDEVENT']._serialized_end=197
  _globals['_ANDROIDPACKAGEREMOVEDEVENT']._serialized_start=199
  _globals['_ANDROIDPACKAGEREMOVEDEVENT']._serialized_end=239
  _globals['_ANDROIDSIGNATUREADDEDEVENT']._serialized_start=241
  _globals['_ANDROIDSIGNATUREADDEDEVENT']._serialized_end=324
  _globals['_ANDROIDSIGNATUREREMOVEDEVENT']._serialized_start=326
  _globals['_ANDROIDSIGNATUREREMOVEDEVENT']._serialized_end=368
  _globals['_SERVICETOKENCREATEDEVENT']._serialized_start=370
  _globals['_SERVICETOKENCREATEDEVENT']._serialized_end=431
  _globals['_SERVICETOKENREMOVEDEVENT']._serialized_start=433
  _globals['_SERVICETOKENREMOVEDEVENT']._serialized_end=494
# @@protoc_insertion_point(module_scope)
