# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto_files import push_console_pb2 as proto__files_dot_push__console__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto_files/push_console_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DeleteStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DeleteApp = channel.unary_unary(
                '/kc_push_console_v1.Delete/DeleteApp',
                request_serializer=proto__files_dot_push__console__pb2.DeleteAppRequest.SerializeToString,
                response_deserializer=proto__files_dot_push__console__pb2.DeleteReply.FromString,
                _registered_method=True)
        self.DeleteSignatureFromApp = channel.unary_unary(
                '/kc_push_console_v1.Delete/DeleteSignatureFromApp',
                request_serializer=proto__files_dot_push__console__pb2.DeleteSignatureFromAppRequest.SerializeToString,
                response_deserializer=proto__files_dot_push__console__pb2.DeleteReply.FromString,
                _registered_method=True)


class DeleteServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DeleteApp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSignatureFromApp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeleteServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DeleteApp': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteApp,
                    request_deserializer=proto__files_dot_push__console__pb2.DeleteAppRequest.FromString,
                    response_serializer=proto__files_dot_push__console__pb2.DeleteReply.SerializeToString,
            ),
            'DeleteSignatureFromApp': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSignatureFromApp,
                    request_deserializer=proto__files_dot_push__console__pb2.DeleteSignatureFromAppRequest.FromString,
                    response_serializer=proto__files_dot_push__console__pb2.DeleteReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kc_push_console_v1.Delete', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kc_push_console_v1.Delete', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Delete(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DeleteApp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kc_push_console_v1.Delete/DeleteApp',
            proto__files_dot_push__console__pb2.DeleteAppRequest.SerializeToString,
            proto__files_dot_push__console__pb2.DeleteReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSignatureFromApp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kc_push_console_v1.Delete/DeleteSignatureFromApp',
            proto__files_dot_push__console__pb2.DeleteSignatureFromAppRequest.SerializeToString,
            proto__files_dot_push__console__pb2.DeleteReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
