# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto_files/push_console.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto_files/push_console.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eproto_files/push_console.proto\x12\x12kc_push_console_v1\"6\n\x10\x44\x65leteAppRequest\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61pp_id\x18\x02 \x01(\t\"Y\n\x1d\x44\x65leteSignatureFromAppRequest\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61pp_id\x18\x02 \x01(\t\x12\x14\n\x0csignature_id\x18\x03 \x01(\t\"\x7f\n\x0b\x44\x65leteReply\x12\x30\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x1f.kc_push_console_v1.DeleteErrorH\x00\x12\x34\n\x07success\x18\x02 \x01(\x0b\x32!.kc_push_console_v1.DeleteSuccessH\x00\x42\x08\n\x06result\"Q\n\x0b\x44\x65leteError\x12+\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x1d.kc_push_console_v1.ErrorCode\x12\x15\n\rerror_message\x18\x02 \x01(\t\"\x0f\n\rDeleteSuccess*\x8b\x01\n\tErrorCode\x12\x1a\n\x16\x45RROR_CODE_UNSPECIFIED\x10\x00\x12\x0f\n\x0b\x42\x41\x44_REQUEST\x10\x01\x12\r\n\tBAD_TOKEN\x10\x02\x12\r\n\tNOT_FOUND\x10\x03\x12\x11\n\rACCESS_DENIED\x10\x04\x12\x0c\n\x08\x43ONFLICT\x10\x05\x12\x12\n\x0eINTERNAL_ERROR\x10\x06\x32\xca\x01\n\x06\x44\x65lete\x12R\n\tDeleteApp\x12$.kc_push_console_v1.DeleteAppRequest\x1a\x1f.kc_push_console_v1.DeleteReply\x12l\n\x16\x44\x65leteSignatureFromApp\x12\x31.kc_push_console_v1.DeleteSignatureFromAppRequest\x1a\x1f.kc_push_console_v1.DeleteReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto_files.push_console_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ERRORCODE']._serialized_start=431
  _globals['_ERRORCODE']._serialized_end=570
  _globals['_DELETEAPPREQUEST']._serialized_start=54
  _globals['_DELETEAPPREQUEST']._serialized_end=108
  _globals['_DELETESIGNATUREFROMAPPREQUEST']._serialized_start=110
  _globals['_DELETESIGNATUREFROMAPPREQUEST']._serialized_end=199
  _globals['_DELETEREPLY']._serialized_start=201
  _globals['_DELETEREPLY']._serialized_end=328
  _globals['_DELETEERROR']._serialized_start=330
  _globals['_DELETEERROR']._serialized_end=411
  _globals['_DELETESUCCESS']._serialized_start=413
  _globals['_DELETESUCCESS']._serialized_end=428
  _globals['_DELETE']._serialized_start=573
  _globals['_DELETE']._serialized_end=775
# @@protoc_insertion_point(module_scope)
